name: font_mapper
description: >-
  A Dart CLI tool that automatically scans font assets and updates the `fonts:` section in your pubspec.yaml file.
homepage: https://github.com/congthanhng/font_mapper
repository: https://github.com/congthanhng/font_mapper
funding:
  - https://www.buymeacoffee.com/congthanhng
topics:
  - fonts
  - pubspec
  - cli
  - mapper
  - font

version: 1.0.0

environment:
  sdk: '>=2.18.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
